# Generated by Django 3.1.1 on 2020-11-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_remove_college_references'),
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='colleges',
            field=models.ManyToManyField(blank=True, null=True, to='colleges.College'),
        ),
    ]
