# Generated by Django 3.1.1 on 2020-11-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencelink',
            options={'ordering': ['description']},
        ),
        migrations.RemoveField(
            model_name='referencelink',
            name='college',
        ),
    ]
