# Generated by Django 3.1.1 on 2020-11-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencelink',
            old_name='reference_url',
            new_name='url',
        ),
    ]
