# Generated by Django 3.1.1 on 2020-11-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201118_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencelink',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
