# Generated by Django 3.1.1 on 2020-11-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0003_remove_major_colleges'),
        ('colleges', '0002_remove_college_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='majors',
            field=models.ManyToManyField(null=True, to='majors.Major'),
        ),
    ]
