# Generated by Django 3.1.1 on 2020-11-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0003_remove_major_colleges'),
        ('colleges', '0003_college_majors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='majors',
            field=models.ManyToManyField(to='majors.Major'),
        ),
    ]
