# Generated by Django 3.1.1 on 2020-11-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_auto_20201123_0916"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="College",),
    ]
