# Generated by Django 3.1 on 2020-08-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="offered_sprint", new_name="offered_spring",
        ),
    ]
