# Generated by Django 3.1.1 on 2020-11-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_delete_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Major',
        ),
    ]
