# Generated by Django 3.1.1 on 2020-09-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0003_auto_20200902_1401")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="in_enviroe",
            field=models.BooleanField(blank=True, default=True, null=True),
        )
    ]
