# Generated by Django 3.1.1 on 2020-09-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0004_course_in_enviroe")]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("courses", models.ManyToManyField(to="courses.Course")),
            ],
            options={"ordering": ["abbreviation"]},
        )
    ]
