# Generated by Django 3.1.1 on 2020-09-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("courses", "0005_major")]

    operations = [migrations.RemoveField(model_name="course", name="in_enviro")]
