# Generated by Django 3.1.1 on 2020-09-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_in_enviro'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
