# Generated by Django 3.1.1 on 2020-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_major_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
