# Generated by Django 3.1.1 on 2020-09-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_major_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
