# Generated by Django 3.1.1 on 2020-09-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0009_course_slug")]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("majors", models.ManyToManyField(to="courses.Major")),
            ],
            options={"ordering": ["abbreviation"]},
        )
    ]
