# Generated by Django 3.1.1 on 2020-09-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="up_equivalent",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
