# Generated by Django 3.1.1 on 2020-09-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_course_up_equivalent"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
