# Generated by Django 3.1.1 on 2020-09-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
